name: 'Github Action Warmup ASG'
description: 'Warmup EC2 to Deploy application'
inputs:
  asg-names:  # id of input 1
    description: 'Autoscaling group name'
    required: true
  asg-names2:  # id of input 2 
    description: 'Autoscaling group name'
    required: false
  asg-names3:  # id of input 3
    description: 'Autoscaling group name'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.asg-names }}
    - ${{ inputs.asg-names2 }}
    - ${{ inputs.asg-names3 }}
